### ISSUE TITLE
Add link share code

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/old-rails-version-of-mehr-schulferien.de#10]
Add the needed HTML code for anybody to link to this page.

**Comment by siaw23** [comment]
Do you plan on adding social media share buttons as well?

**Comment by wintermeyer** [comment]
> Do you plan on adding social media share buttons as well?

Man you know how to put a finger in a wound. ;-)

Answer: We should.

**Comment by wintermeyer** [comment]
https://github.com/mehr-schulferien-de/www.mehr-schulferien.de/issues/578
https://github.com/mehr-schulferien-de/www.mehr-schulferien.de/issues/579
