### ISSUE TITLE
Fix Responsiveness

### ISSUE THREAD

**Issue by siaw23** [wintermeyer/old-rails-version-of-mehr-schulferien.de#11]
The styling doesn't look right on this page: https://www.mehr-schulferien.de/ferien/d/schule/38122-grundschule-gartenstadt

<img width="1219" alt="Screenshot 2021-01-07 at 00 58 57" src="https://user-images.githubusercontent.com/4806407/103834423-a4c14700-5083-11eb-949d-d77f4708a588.png">

**Comment by wintermeyer** [comment]
https://github.com/mehr-schulferien-de/www.mehr-schulferien.de/issues/577
