### ISSUE TITLE
Ad top traffic keywords to the HTML title

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/old-rails-version-of-mehr-schulferien.de#13]
Here is a list of top traffic keywords which fit perfectly for mehr-schulferien.de:

sommerferien 2020
ferien 2020
feiertage 2020
ferien nrw 2020
sommerferien nrw 2020
ferien bayern 2020
feiertage nrw 2020
schulferien 2020
osterferien 2020
ferien nrw
herbstferien nrw 2020
sommerferien nrw
herbstferien nrw
herbstferien 2020
ferien niedersachsen
ferien niedersachsen 2020
ferien sachsen 2020
schulferien nrw 2020
ferien hessen 2020
herbstferien
pfingsten 2021
ferien bayern
schulferien bayern 2020

**Comment by wintermeyer** [comment]
Same goes for the meta description.

**Comment by wintermeyer** [comment]
Max 160 characters.

**Comment by siaw23** [comment]
🎗 We'll be optimising for 2021 though, so 2020 should be replaced with 2021 in the keywords.

**Comment by wintermeyer** [comment]
https://github.com/mehr-schulferien-de/www.mehr-schulferien.de/issues/576
